version: '3'

services:
  redis-master:
    image: redis
    container_name: redis-master
    command: redis-server --appendonly yes
    networks:
      - redis-net

  redis-slave:
    image: redis
    container_name: redis-slave
    command: redis-server --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
